"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.SchemaLibrary = exports.ModelAction = exports.defaultConfigs = exports.configSchema = void 0;
const zod_1 = require("zod");
const configBoolean = zod_1.z.enum(['true', 'false']).transform((arg) => JSON.parse(arg));
const configNumber = zod_1.z
    .union([zod_1.z.string(), zod_1.z.number()])
    .transform((arg) => (typeof arg === 'number' ? arg : parseInt(arg, 10)))
    .pipe(zod_1.z.number());
const configArray = (items) => zod_1.z
    .union([zod_1.z.array(items), zod_1.z.string()])
    .transform((arg) => (Array.isArray(arg) ? arg : arg.split(',').map((item) => item.trim())))
    .pipe(zod_1.z.array(items));
// Schema validation library support (zod only)
const SchemaLibrary = {
    zod: 'zod',
};
exports.SchemaLibrary = SchemaLibrary;
const schemaLibraryEnum = zod_1.z.nativeEnum(SchemaLibrary);
// Enhanced model actions
const ModelAction = {
    // Basic CRUD
    create: 'create',
    createMany: 'createMany',
    findFirst: 'findFirst',
    findFirstOrThrow: 'findFirstOrThrow',
    findMany: 'findMany',
    findUnique: 'findUnique',
    findUniqueOrThrow: 'findUniqueOrThrow',
    update: 'update',
    updateMany: 'updateMany',
    upsert: 'upsert',
    delete: 'delete',
    deleteMany: 'deleteMany',
    // Advanced operations
    aggregate: 'aggregate',
    groupBy: 'groupBy',
    count: 'count',
    findRaw: 'findRaw',
    aggregateRaw: 'aggregateRaw',
};
exports.ModelAction = ModelAction;
exports.configSchema = zod_1.z.object({
    // Basic configuration
    output: zod_1.z.string().default('./src/generated/orpc'),
    // When empty, generator will inline a minimal Context type and import PrismaClient types directly
    contextPath: zod_1.z.string().default(''),
    // Schema validation
    schemaLibrary: schemaLibraryEnum.default('zod'),
    generateInputValidation: configBoolean.default('true'),
    generateOutputValidation: configBoolean.default('true'),
    strictValidation: configBoolean.default('true'),
    // Always import schemas generated by 'prisma-zod-generator' when using 'zod'
    // Programmatic zod generator output path (relative to oRPC output dir or a module specifier)
    zodSchemasOutputPath: zod_1.z.string().default('./zod-schemas'),
    // Module specifier or relative path to import from (defaults to zodSchemasOutputPath)
    externalZodImportPath: zod_1.z.string().default('./zod-schemas'),
    // prisma-zod-generator DateTime handling strategy
    // - 'date' (z.date())
    // - 'coerce' (z.coerce.date())
    // - 'isoString' (z.string().regex(ISO).transform(v => new Date(v)))
    zodDateTimeStrategy: zod_1.z.enum(['date', 'coerce', 'isoString']).default('coerce'),
    // Path to custom zod.config.json file (relative to schema or absolute)
    zodConfigPath: zod_1.z.string().optional(),
    // Documentation / HTTP layer configuration
    // Documentation / HTTP settings
    apiTitle: zod_1.z.string().default('Generated API'),
    apiDescription: zod_1.z.string().default('Auto-generated API from Prisma schema'),
    apiVersion: zod_1.z.string().default('1.0.0'),
    serverPort: configNumber.default(3000),
    apiPrefix: zod_1.z.string().default(''),
    // Runtime configuration
    // Model operations
    // Accept any string list, then filter to supported actions to remain backward-compatible
    generateModelActions: configArray(zod_1.z.string())
        .transform((arr) => arr.filter((a) => Object.values(ModelAction).includes(a)))
        .default(Object.values(ModelAction)),
    showModelNameInProcedure: configBoolean.default('true'),
    enableSoftDeletes: configBoolean.default('false'),
    generateRelationResolvers: configBoolean.default('true'),
    // Developer experience
    generateDocumentation: configBoolean.default('false'),
    generateTests: configBoolean.default('false'),
    enableDebugLogging: configBoolean.default('false'),
    // Code generation options
    useBarrelExports: configBoolean.default('true'),
    codeStyle: zod_1.z.enum(['prettier', 'none']).default('prettier'),
    // Response shaping / integration modes
    // When false, handlers return raw Prisma results instead of { success, data, meta } envelope
    wrapResponses: configBoolean.default('false'),
    // Error handling
    generateErrorHandling: configBoolean.default('true'),
    // Compatibility
    prismaClientPath: zod_1.z.string().default('@prisma/client'),
});
// Default configuration for different scenarios
exports.defaultConfigs = {
    basic: {},
    production: {},
    serverless: {},
    enterprise: {
        generateTests: 'true',
    },
};
//# sourceMappingURL=schema.js.map