/**
 * Standardized @autogenerated header for all prisma-orpc-generator output files.
 *
 * Must appear in the first 10 lines so doc-gen drift detection can identify
 * generated files by scanning only the header area.
 */
export declare const AUTOGEN_HEADER = "/**\n * @autogenerated \u2014 DO NOT EDIT\n * Generated by: prisma-orpc-generator\n */\n\n";
//# sourceMappingURL=autogen-header.d.ts.map