"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.AUTOGEN_HEADER = void 0;
/**
 * Standardized @autogenerated header for all prisma-orpc-generator output files.
 *
 * Must appear in the first 10 lines so doc-gen drift detection can identify
 * generated files by scanning only the header area.
 */
exports.AUTOGEN_HEADER = `/**
 * @autogenerated — DO NOT EDIT
 * Generated by: prisma-orpc-generator
 */

`;
//# sourceMappingURL=autogen-header.js.map