/**
 * Standardized @autogenerated header for all prisma-orpc-generator output files.
 *
 * Must appear in the first 10 lines so doc-gen drift detection can identify
 * generated files by scanning only the header area.
 */
export const AUTOGEN_HEADER = `/**
 * @autogenerated — DO NOT EDIT
 * Generated by: prisma-orpc-generator
 */

`;
